### ISSUE TITLE
Poll rate is fixed to 60 secs which is too long

### ISSUE THREAD

**Issue by kgbalphabeta** [lewei50/ha_iammeter#10]
Can't adjust poll rate during integration. This is fixed to 60 secs

**Comment by miwyf** [comment]
ha_iammeter uses the http get mode to obtain data. The default is to obtain data once every 60 seconds. If you want to obtain data faster, you can use [ha_iammeter_modbus](https://github.com/lewei50/ha_iammeter_modbus) integration.

**Comment by miwyf** [comment]
Automation can also reduce the sensor acquisition interval.
`alias: Fast Update Sensors
description: Fast Update Sensors
trigger:
  - platform: time_pattern
    seconds: /3
condition: []
action:
  - service: homeassistant.update_entity
    target:
      entity_id:
        - sensor.solarpv_power_a
        - sensor.solarpv_power_b
        - sensor.solarpv_power_c
    data: {}
mode: single`
