### ISSUE TITLE
Failed to set up HA Core 2023.5.0

### ISSUE THREAD

**Issue by soheiladeli** [lewei50/ha_iammeter#6]
Hi, have issue with the home assistant core integration 2023.5.0. The HACS integration fails to set up:
Home Assistant core 2023.5.0
Frontend 20230503.1 - latest

Logger: homeassistant.config_entries
Source: custom_components/iammeter_http/init.py:25
Integration: Iammeter_http
First occurred: 5:10:34 PM (1 occurrences)
Last logged: 5:10:34 PM

Error setting up entry i_meter_fc621daa for iammeter_http
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
File "/root/.homeassistant/custom_components/iammeter_http/init.py", line 25, in async_setup_entry
hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

<img width="219" alt="image" src="https://user-images.githubusercontent.com/20199950/236137068-d3c9a81d-f963-4b19-89a1-3a284a341f42.png">

**Comment by grahambrown11** [comment]
I have the same issue...
Open `custom_components/iammeter_http/__init__.py` in an editor (I use the VSCode Addon)
and update line 25 to
```python
await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
```
Restart HA and the integration is working again and getting the enery data 😄 
I'll see if I have time I'll clone the project and submit a PR...

**Comment by soheiladeli** [comment]
@grahambrown11 , thanks, that fixed it 👍

**Comment by grahambrown11** [comment]
PR submitted #7

**Comment by sinemaker** [comment]
I am having the same problem with six iammeter devices.  I have tried deleting, re-installing.  I added the word "await" to line 25 as suggested but that had no impact.

**Comment by grahambrown11** [comment]
@sinemaker the whole line needs to change... it used a deprecated method and the HomeAssistant maintainers removed a lot of deprecations this release...
the function was `async_setup_platforms` and now needs to be `async_forward_entry_setups` with the `await`

**Comment by miwyf** [comment]
Issue resolved, many thanks to @grahambrown11  for the PR submitted

**Comment by grahambrown11** [comment]
> Issue resolved, many thanks to @grahambrown11 for the PR submitted

@miwyf I have updated via HACS and can confirm all working now 🎉 , you may close this issue 🚀
