### ISSUE TITLE
Error while setting up iammeter platform for sensor

### ISSUE THREAD

**Issue by klugev303** [lewei50/ha_iammeter#8]
I have a problem: if the device is turned off at the time HomeAssistant starts (I have one device connected to the generator, and it works ), then after the device appears on the network (and at the same time transmits information to the cloud correctly) in this integration it does not appear, and a manual restart of HomeAssistant is required, which is not correct.
I am attaching the logs: **[iammeter_log.txt](https://github.com/lewei50/ha_iammeter/files/12748748/iammeter_log.txt)**
 Tell me how you can restart your integration manually?
I wanted to configure the restart of this integration manually via
API URL when accessed using the POST method will restart:
<HA_URL>/api/config/config_entries/entry/<Integration_ID>/reload
But where can you get the "Integration_ID" for your integration?
Or maybe you yourself can somehow fix this problem by polling the availability of the devices listed in it?

**Comment by yangbo1979** [comment]
fixed in release 1.0.14.
